#### Description:

In [ ]:
'''
    I aim to Build a Model That Predicat the salary based on:
        (city, occupation, field, years_of_experience, employment_type, education_level, gender, company_size)
'''

'\n    I aim to Build a Model That Predicat the salary based on:\n        (city, occupation, field, years_of_experience, employment_type, education_level, gender, company_size)\n'

#### Import Data and Select Features

In [2]:
# Import Packages
import pandas as pd

In [3]:
# %ls drive/MyDrive/job_market_dataset.csv
data = pd.read_csv("drive/MyDrive/job_market_dataset.csv")
data.head(2)

,country,city,occupation,field,years_of_experience,salary,employment_type,education_level,gender,company_size,year,month
0,Switzerland,Zurich,Operations Manager,Operations,16,359609.0,work_from_home,Master,Male,Large,2023,8
1,India,Bangalore,HR Analyst,Human Resources,12,79059.0,part_time,PhD,Male,Large,2023,5

In [8]:
# Delete Features (year, month)
cp_data = data.drop(["year", "month"], axis=1)
cp_data = cp_data.iloc[:100000]
cp_data.head(4)

,country,city,occupation,field,years_of_experience,salary,employment_type,education_level,gender,company_size
0,Switzerland,Zurich,Operations Manager,Operations,16,359609.0,work_from_home,Master,Male,Large
1,India,Bangalore,HR Analyst,Human Resources,12,79059.0,part_time,PhD,Male,Large
2,Sweden,Stockholm,Software Engineer,Technology,10,258077.0,freelance,Master,Male,Enterprise
3,South Korea,Seoul,Operations Manager,Operations,7,252282.0,part_time,Master,Female,Large

#### Feature Encoding

In [9]:
from sklearn.preprocessing import LabelEncoder # for Mapping / Label Encoder
from sklearn.preprocessing import OneHotEncoder # for One Hot Encoding

In [10]:
# Mapping/Label Encoding This Varaibles
company_size_map = {'Large': 3, 'Enterprise': 2, 'Medium': 1, 'Small': 0}
cp_data["company_size"] = [company_size_map[v] for v in cp_data["company_size"]]

gender_map = {'Male': 0, 'Female': 1, 'Other': 2}
cp_data["gender"] = [gender_map[v] for v in cp_data["gender"]]

education_level_map = {'PhD': 3, 'Master': 2, 'Bachelor': 1, 'High School': 0}
cp_data["education_level"] = [education_level_map[v] for v in cp_data["education_level"]]

# One-Hot-Encoding
one_hot_encoder = OneHotEncoder()
cp_data = pd.get_dummies(cp_data, columns=["field", "employment_type", "city", "country", "occupation"])
cp_data.head(3)

,years_of_experience,salary,education_level,gender,company_size,field_Business,field_Design,field_Finance,field_Human Resources,field_Marketing,...,occupation_Cloud Engineer,occupation_Data Analyst,occupation_Data Scientist,occupation_Financial Analyst,occupation_HR Analyst,occupation_Marketing Specialist,occupation_Operations Manager,occupation_Product Manager,occupation_Software Engineer,occupation_UX Designer
0,16,359609.0,2,0,3,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
1,12,79059.0,3,0,3,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
2,10,258077.0,2,0,2,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

#### Split Data

In [11]:
# Get X and y
X = cp_data.drop("salary", axis=1)
y = cp_data["salary"]

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
# Split Train Set, Test Set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

#### Data Normalisation

In [14]:
cp_data.head(4)

,years_of_experience,salary,education_level,gender,company_size,field_Business,field_Design,field_Finance,field_Human Resources,field_Marketing,...,occupation_Cloud Engineer,occupation_Data Analyst,occupation_Data Scientist,occupation_Financial Analyst,occupation_HR Analyst,occupation_Marketing Specialist,occupation_Operations Manager,occupation_Product Manager,occupation_Software Engineer,occupation_UX Designer
0,16,359609.0,2,0,3,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
1,12,79059.0,3,0,3,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
2,10,258077.0,2,0,2,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,7,252282.0,2,1,3,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False

In [15]:
# from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from copy import deepcopy

In [16]:
max_scaled_dataset = deepcopy(cp_data)

In [17]:
min_max_scaler = MinMaxScaler(feature_range=(0, 1))
cols = max_scaled_dataset.columns
for col in cols:
       max_scaled_dataset[col] = max_scaled_dataset[col] / int(max_scaled_dataset[col].max())

max_scaled_dataset.describe()

,years_of_experience,salary,education_level,gender,company_size,field_Business,field_Design,field_Finance,field_Human Resources,field_Marketing,...,occupation_Cloud Engineer,occupation_Data Analyst,occupation_Data Scientist,occupation_Financial Analyst,occupation_HR Analyst,occupation_Marketing Specialist,occupation_Operations Manager,occupation_Product Manager,occupation_Software Engineer,occupation_UX Designer
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,...,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,0.473642,0.558600,0.501403,0.501615,0.499783,0.08157,0.083990,0.082910,0.083530,0.083670,...,0.083120,0.084270,0.081860,0.082910,0.083530,0.083670,0.083520,0.084340,0.083650,0.083990
std,0.287197,0.232097,0.373404,0.407838,0.372781,0.27371,0.277374,0.275748,0.276683,0.276894,...,0.276065,0.277794,0.274153,0.275748,0.276683,0.276894,0.276668,0.277898,0.276864,0.277374
min,0.000000,0.032432,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.240000,0.384065,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.480000,0.540528,0.666667,0.500000,0.666667,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.720000,0.722252,1.000000,1.000000,0.666667,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

#### Model Building (Random Forest)

In [18]:
from sklearn.ensemble import RandomForestRegressor

In [19]:
# Build a Model
model = RandomForestRegressor(n_estimators=100, oob_score=True)

In [20]:
# Fit Training Set with prediction result
model.fit(X_train, y_train)

RandomForestRegressor(oob_score=True)

In [63]:
# Prediction
y_pred = model.predict(X_test)

In [ ]:
# Get Test Dataset Frame
y_test_df = pd.DataFrame(y_test, columns=["salary"])
y_test_df.reset_index(inplace=True)
y_test_df = y_test_df.drop("index", axis=1)
y_test_df.head(3)

     salary
0  176284.0
1  157717.0
2  186763.0

In [ ]:
# Get Predction DataSet Frame
y_pred_df = pd.DataFrame(y_pred, columns=["salary_pred"])
y_pred_df.head(3)

   salary_pred
0    189156.57
1    177301.28
2    171190.58

In [93]:
# Combine The Two DataSet
y_pred_real_df = pd.concat([y_pred_df, y_test_df], axis=1)
y_pred_real_df.head(3)

   salary_pred    salary
0    189156.57  176284.0
1    177301.28  157717.0
2    171190.58  186763.0

#### Model Improvements

In [105]:
'''
    - MAE (Mean Absolute Error) → average difference
    - RMSE (Root Mean Squared Error) → penalizes big errors
    - R² → % of variance explained by model
    - Result Visualisation
'''

'\n    - MAE (Mean Absolute Error) → average difference\n    - RMSE (Root Mean Squared Error) → penalizes big errors\n    - R² → % of variance explained by model\n    - Result Visualisation\n'

In [120]:
from sklearn.metrics import mean_absolute_error as mae, root_mean_squared_error as rmse, r2_score as r_2
from math import sqrt

In [128]:
# Get Mean Absolute Error (MAE)
mae_val = sum(abs(y_pred_real_df["salary"] - y_pred_real_df["salary_pred"])) / y_pred_real_df["salary"].size
print(mae_val)
mae(y_pred=y_pred_real_df["salary_pred"], y_true=y_pred_real_df["salary"])

22895.230862935583

22895.230862935583

In [129]:
# Root Mean Squared Error (RMSE)
rmse_val = sqrt(sum(pow(y_pred_real_df["salary"] - y_pred_real_df["salary_pred"], 2)) / y_test.count())
print(rmse_val)
rmse(y_pred=y_pred_real_df["salary_pred"], y_true=y_pred_real_df["salary"])

32007.846789957333

32007.846789957333

In [135]:
# Get R²
mean_y_test_set = y_test.mean()
r_2_val = 1 - (sum(pow(y_pred_real_df["salary"] - y_pred_real_df["salary_pred"], 2)) / sum(pow(y_pred_real_df["salary"] - mean_y_test_set, 2)))
print(r_2_val)

r_2(y_pred=y_pred_real_df["salary_pred"], y_true=y_pred_real_df["salary"])

0.860986180179855

0.860986180179855