#### Description:

In [4]:
'''
    I aim to Build a Model That Predicat the salary based on:
        (city, occupation, field, years_of_experience, employment_type, education_level, gender, company_size)
'''

'\n    I aim to Build a Model That Predicat the salary based on:\n        (city, occupation, field, years_of_experience, employment_type, education_level, gender, company_size)\n'

#### Import Data and Select Features

In [7]:
# Import Packages
import pandas as pd

In [86]:
# take just 100K rows
data = pd.read_csv("./data/job_market_dataset.csv")
data.head(2)

,country,city,occupation,field,years_of_experience,salary,employment_type,education_level,gender,company_size,year,month
0,Switzerland,Zurich,Operations Manager,Operations,16,359609.0,work_from_home,Master,Male,Large,2023,8
1,India,Bangalore,HR Analyst,Human Resources,12,79059.0,part_time,PhD,Male,Large,2023,5

In [87]:
# Delete Features (year, month)
cp_data = data.drop(["year", "month"], axis=1)
cp_data.head(3)

,country,city,occupation,field,years_of_experience,salary,employment_type,education_level,gender,company_size
0,Switzerland,Zurich,Operations Manager,Operations,16,359609.0,work_from_home,Master,Male,Large
1,India,Bangalore,HR Analyst,Human Resources,12,79059.0,part_time,PhD,Male,Large
2,Sweden,Stockholm,Software Engineer,Technology,10,258077.0,freelance,Master,Male,Enterprise

#### Feature Encoding

In [96]:
from sklearn.preprocessing import LabelEncoder # for Mapping / Label Encoder
from sklearn.preprocessing import OneHotEncoder # for One Hot Encoding

In [ ]:
# Mapping/Label Encoding This Varaibles
company_size_map = {'Large': 3, 'Enterprise': 2, 'Medium': 1, 'Small': 0}
cp_data["company_size"] = [company_size_map[v] for v in cp_data["company_size"]]

gender_map = {'Male': 0, 'Female': 1, 'Other': 2}
cp_data["gender"] = [gender_map[v] for v in cp_data["gender"]]

education_level_map = {'PhD': 3, 'Master': 2, 'Bachelor': 1, 'High School': 0}
cp_data["education_level"] = [education_level_map[v] for v in cp_data["education_level"]]

# One-Hot-Encoding
one_hot_encoder = OneHotEncoder()
cp_data = pd.get_dummies(cp_data, columns=["field", "employment_type", "city", "country", "occupation"])
cp_data.head(3)

,years_of_experience,salary,education_level,gender,company_size,field_Business,field_Design,field_Finance,field_Human Resources,field_Marketing,...,occupation_Cloud Engineer,occupation_Data Analyst,occupation_Data Scientist,occupation_Financial Analyst,occupation_HR Analyst,occupation_Marketing Specialist,occupation_Operations Manager,occupation_Product Manager,occupation_Software Engineer,occupation_UX Designer
0,16,359609.0,2,0,3,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
1,12,79059.0,3,0,3,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
2,10,258077.0,2,0,2,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

#### Split Data

In [103]:
# Get X and y
X = cp_data.drop("salary", axis=1)
y = cp_data["salary"]

In [104]:
from sklearn.model_selection import train_test_split

In [113]:
# Split Train Set, Test Set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

#### Data Normalisation

In [116]:
# from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [ ]:
# Salary Normalisation Or Scaling
# min_max_scal = MinMaxScaler(feature_range=(0, 1))
# nd_data = min_max_scal.fit_transform(X=X_train, y=y_train)
# df = pd.DataFrame(nd_data, columns=["country", "city", "occupation", "field", "years_of_experience", "employment_type", "education_level", "gender", "company_size"])
# df

min_max_scaler = MinMaxScaler(feature_range=(0, 1))
nd_array = min_max_scaler.fit_transform(X_train, y_train)
cp_data = pd.DataFrame(nd_array, columns=['years_of_experience', 'salary', 'education_level', 'gender',
       'company_size', 'field_Business', 'field_Design', 'field_Finance',
       'field_Human Resources', 'field_Marketing', 'field_Operations',
       'field_Technology', 'employment_type_freelance',
       'employment_type_full_time', 'employment_type_internship',
       'employment_type_part_time', 'employment_type_work_from_home',
       'city_Amsterdam', 'city_Auckland', 'city_Bangalore', 'city_Berlin',
       'city_Cape Town', 'city_Dubai', 'city_Dublin', 'city_London',
       'city_Madrid', 'city_Mexico City', 'city_Milan', 'city_New York',
       'city_Paris', 'city_San Francisco', 'city_Sao Paulo', 'city_Seoul',
       'city_Singapore', 'city_Stockholm', 'city_Sydney', 'city_Tokyo',
       'city_Toronto', 'city_Zurich', 'country_Australia', 'country_Brazil',
       'country_Canada', 'country_France', 'country_Germany', 'country_India',
       'country_Ireland', 'country_Italy', 'country_Japan', 'country_Mexico',
       'country_Netherlands', 'country_New Zealand', 'country_Singapore',
       'country_South Africa', 'country_South Korea', 'country_Spain',
       'country_Sweden', 'country_Switzerland', 'country_United Arab Emirates',
       'country_United Kingdom', 'country_United States',
       'occupation_AI Engineer', 'occupation_Business Analyst',
       'occupation_Cloud Engineer', 'occupation_Data Analyst',
       'occupation_Data Scientist', 'occupation_Financial Analyst',
       'occupation_HR Analyst', 'occupation_Marketing Specialist',
       'occupation_Operations Manager', 'occupation_Product Manager',
       'occupation_Software Engineer', 'occupation_UX Designer'])
cp_data

ValueError: Shape of passed values is (350000, 71), indices imply (350000, 72)

#### Model Building (Random Forest)

In [71]:
from sklearn.ensemble import RandomForestRegressor

In [72]:
# Build a Model
model = RandomForestRegressor(n_estimators=100, oob_score=True)

In [73]:
# Fit Training Set with prediction result
model.fit(X_train, y_train)

RandomForestRegressor(oob_score=True)

In [ ]:
# Prediction
y_pred = model.predict(X_test)

array([275232.83683333, 134047.13483333, 263269.96341667, ...,
       295631.92333333, 135634.055     , 320338.06319048])

In [83]:
y_pred

array([275232.83683333, 134047.13483333, 263269.96341667, ...,
       295631.92333333, 135634.055     , 320338.06319048])

#### Model Improvements

In [85]:
# Get OOB (Out of Bug) Error
'''
    MAE (Mean Absolute Error) → average difference
    RMSE (Root Mean Squared Error) → penalizes big errors
    R² → % of variance explained by model
'''
model.oob_score_

0.8884588678409701